<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="9" passed="2" failed="7" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-11T19:54:28 AST" name="IcNetbanking" finished-at="2023-05-11T19:55:45 AST" duration-ms="77079">
    <groups>
    </groups>
    <test started-at="2023-05-11T19:54:28 AST" name="BankingApp Test" finished-at="2023-05-11T19:55:45 AST" duration-ms="77079">
      <class name="com.icnetbanking.testcases.TC_Login_002_Test">
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Login_002_Test@4ec4f3a0]" started-at="2023-05-11T19:54:55 AST" name="setup" finished-at="2023-05-11T19:54:58 AST" duration-ms="2539" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Login_002_Test.InvalidCredentialsLogin(java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="InvalidCredentialsLogin(java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.icnetbanking.testcases.TC_Login_002_Test@4ec4f3a0]" started-at="2023-05-11T19:54:58 AST" name="InvalidCredentialsLogin" data-provider="gettestdatafromexcel" finished-at="2023-05-11T19:55:02 AST" duration-ms="4569" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[poornima1982@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[selenium@1234]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Warning: No match for E-Mail Address and/or Password.]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidCredentialsLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Login_002_Test@4ec4f3a0]" started-at="2023-05-11T19:55:02 AST" name="teardown" finished-at="2023-05-11T19:55:02 AST" duration-ms="255" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Login_002_Test@4ec4f3a0]" started-at="2023-05-11T19:55:02 AST" name="setup" finished-at="2023-05-11T19:55:05 AST" duration-ms="2529" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Login_002_Test.InvalidCredentialsLogin(java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="InvalidCredentialsLogin(java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.icnetbanking.testcases.TC_Login_002_Test@4ec4f3a0]" started-at="2023-05-11T19:55:05 AST" name="InvalidCredentialsLogin" data-provider="gettestdatafromexcel" finished-at="2023-05-11T19:55:13 AST" duration-ms="7767" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[swetha2010@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[selenium@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Warning: No match for E-Mail Address and/or Password.]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.icnetbanking.testcases.TC_Login_002_Test.InvalidCredentialsLogin(TC_Login_002_Test.java:47)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidCredentialsLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Login_002_Test@4ec4f3a0]" started-at="2023-05-11T19:55:13 AST" name="teardown" finished-at="2023-05-11T19:55:13 AST" duration-ms="268" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Login_002_Test@4ec4f3a0]" started-at="2023-05-11T19:55:13 AST" name="setup" finished-at="2023-05-11T19:55:16 AST" duration-ms="2477" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Login_002_Test.InvalidCredentialsLogin(java.lang.String,java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="InvalidCredentialsLogin(java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.icnetbanking.testcases.TC_Login_002_Test@4ec4f3a0]" started-at="2023-05-11T19:55:16 AST" name="InvalidCredentialsLogin" data-provider="gettestdatafromexcel" finished-at="2023-05-11T19:55:20 AST" duration-ms="4040" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[latha@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[pass@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Warning: No match for E-Mail Address and/or Password.]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.icnetbanking.testcases.TC_Login_002_Test.InvalidCredentialsLogin(TC_Login_002_Test.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidCredentialsLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Login_002_Test@4ec4f3a0]" started-at="2023-05-11T19:55:20 AST" name="teardown" finished-at="2023-05-11T19:55:20 AST" duration-ms="309" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.icnetbanking.testcases.TC_Login_002_Test -->
      <class name="com.icnetbanking.testcases.TC_Register_003_Test">
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Register_003_Test@223191a6]" started-at="2023-05-11T19:55:20 AST" name="setup" finished-at="2023-05-11T19:55:23 AST" duration-ms="2505" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Register_003_Test.RegisterNewAccount(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="RegisterNewAccount(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.icnetbanking.testcases.TC_Register_003_Test@223191a6]" started-at="2023-05-11T19:55:23 AST" name="RegisterNewAccount" data-provider="gettestdatafromexcel" finished-at="2023-05-11T19:55:28 AST" duration-ms="5158" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mayuri]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[kamal]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[mayuri2010@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[4545454]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[test@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.icnetbanking.testcases.TC_Register_003_Test.RegisterNewAccount(TC_Register_003_Test.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegisterNewAccount -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Register_003_Test@223191a6]" started-at="2023-05-11T19:55:28 AST" name="teardown" finished-at="2023-05-11T19:55:29 AST" duration-ms="413" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Register_003_Test@223191a6]" started-at="2023-05-11T19:55:29 AST" name="setup" finished-at="2023-05-11T19:55:32 AST" duration-ms="2880" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Register_003_Test.RegisterNewAccount(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="RegisterNewAccount(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.icnetbanking.testcases.TC_Register_003_Test@223191a6]" started-at="2023-05-11T19:55:32 AST" name="RegisterNewAccount" data-provider="gettestdatafromexcel" finished-at="2023-05-11T19:55:36 AST" duration-ms="4584" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[jamuna]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[soundar]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[jamuna1234@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[5454454]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[test@124]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.icnetbanking.testcases.TC_Register_003_Test.RegisterNewAccount(TC_Register_003_Test.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegisterNewAccount -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Register_003_Test@223191a6]" started-at="2023-05-11T19:55:36 AST" name="teardown" finished-at="2023-05-11T19:55:37 AST" duration-ms="314" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Register_003_Test@223191a6]" started-at="2023-05-11T19:55:37 AST" name="setup" finished-at="2023-05-11T19:55:40 AST" duration-ms="2838" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Register_003_Test.RegisterNewAccount(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="RegisterNewAccount(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:1, instance:com.icnetbanking.testcases.TC_Register_003_Test@223191a6]" started-at="2023-05-11T19:55:40 AST" name="RegisterNewAccount" data-provider="gettestdatafromexcel" finished-at="2023-05-11T19:55:44 AST" duration-ms="4630" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[nandhini]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[bala]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[nandhini7890@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[4545435]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[test@125]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.icnetbanking.testcases.TC_Register_003_Test.RegisterNewAccount(TC_Register_003_Test.java:57)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegisterNewAccount -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Register_003_Test@223191a6]" started-at="2023-05-11T19:55:44 AST" name="teardown" finished-at="2023-05-11T19:55:45 AST" duration-ms="331" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.icnetbanking.testcases.TC_Register_003_Test -->
      <class name="com.icnetbanking.testcases.TC_Login_001_Test">
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Login_001_Test@3e58a80e]" started-at="2023-05-11T19:54:28 AST" name="setup" finished-at="2023-05-11T19:54:32 AST" duration-ms="4012" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Login_001_Test.CheckValidUserPwdforLogin() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="CheckValidUserPwdforLogin()[pri:1, instance:com.icnetbanking.testcases.TC_Login_001_Test@3e58a80e]" started-at="2023-05-11T19:54:32 AST" name="CheckValidUserPwdforLogin" finished-at="2023-05-11T19:54:36 AST" duration-ms="4217" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckValidUserPwdforLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Login_001_Test@3e58a80e]" started-at="2023-05-11T19:54:36 AST" name="teardown" finished-at="2023-05-11T19:54:36 AST" duration-ms="270" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Login_001_Test@3e58a80e]" started-at="2023-05-11T19:54:36 AST" name="setup" finished-at="2023-05-11T19:54:39 AST" duration-ms="2677" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Login_001_Test.CheckInValidUserPwdforLogin(java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="CheckInValidUserPwdforLogin(java.lang.String,java.lang.String)[pri:2, instance:com.icnetbanking.testcases.TC_Login_001_Test@3e58a80e]" started-at="2023-05-11T19:54:39 AST" name="CheckInValidUserPwdforLogin" data-provider="CustomdpNinjaLogin" finished-at="2023-05-11T19:54:47 AST" duration-ms="7739" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[swetha2010@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[selenium@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.icnetbanking.testcases.TC_Login_001_Test.CheckInValidUserPwdforLogin(TC_Login_001_Test.java:94)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckInValidUserPwdforLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Login_001_Test@3e58a80e]" started-at="2023-05-11T19:54:47 AST" name="teardown" finished-at="2023-05-11T19:54:47 AST" duration-ms="372" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method is-config="true" signature="setup(java.lang.reflect.Method)[pri:0, instance:com.icnetbanking.testcases.TC_Login_001_Test@3e58a80e]" started-at="2023-05-11T19:54:47 AST" name="setup" finished-at="2023-05-11T19:54:50 AST" duration-ms="2809" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.icnetbanking.testcases.TC_Login_001_Test.CheckInValidUserValidPwdforLogin(java.lang.String,java.lang.String) throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="CheckInValidUserValidPwdforLogin(java.lang.String,java.lang.String)[pri:3, instance:com.icnetbanking.testcases.TC_Login_001_Test@3e58a80e]" started-at="2023-05-11T19:54:50 AST" name="CheckInValidUserValidPwdforLogin" data-provider="CustomdpNinjaLogin" finished-at="2023-05-11T19:54:54 AST" duration-ms="3972" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[latha@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[selenium@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.icnetbanking.testcases.TC_Login_001_Test.CheckInValidUserValidPwdforLogin(TC_Login_001_Test.java:123)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckInValidUserValidPwdforLogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.icnetbanking.testcases.TC_Login_001_Test@3e58a80e]" started-at="2023-05-11T19:54:54 AST" name="teardown" finished-at="2023-05-11T19:54:55 AST" duration-ms="267" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.icnetbanking.testcases.TC_Login_001_Test -->
    </test> <!-- BankingApp Test -->
  </suite> <!-- IcNetbanking -->
</testng-results>
